import type { Metadata } from "next";
import CustomCursor from "@/components/CustomCursor";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DependenciesInjection from "@/components/DependenciesInjection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DependenciesInjection>
          {children}
        </DependenciesInjection>
      </body>
    </html>
  );
}
